apiVersion: v1
kind: Pod
metadata:
  annotations:
    image-tag: "true"
  labels:
    app: fedora
  ownerReferences:
  - apiVersion: apps/v1
    kind: ReplicaSet
spec:
  containers:
  - name: fedora
status:
  phase: Running
