---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageimports.tagger.dev
spec:
  group: tagger.dev
  names:
    kind: ImageImport
    listKind: ImageImportList
    plural: imageimports
    singular: imageimport
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    additionalPrinterColumns:
    - description: Insecure
      jsonPath: .spec.insecure
      name: insecure
      type: boolean
    - description: Mirroring
      jsonPath: .spec.mirror
      name: mirror
      type: boolean
    - description: Target Image
      jsonPath: .spec.targetImage
      name: targetImage
      type: string
    - description: Imported At
      jsonPath: .status.hashReference.importedAt
      name: importedAt
      type: string
    - description: Image Reference
      jsonPath: .status.hashReference.imageReference
      name: imageReference 
      type: string
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetImage:
                type: string
              from:
                type: string
              mirror:
                type: boolean
              insecure:
                type: boolean
          status:
            type: object
            properties:
              importAttempts:
                type: array
                nullable: true
                items:
                  type: object
                  properties:
                    when:
                      type: string
                      nullable: true
                    succeed:
                      type: boolean
                    reason:
                      type: string
              hashReference:
                type: object
                properties:
                  from:
                    type: string
                  importedAt:
                    type: string
                  imageReference:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.tagger.dev
spec:
  group: tagger.dev 
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    additionalPrinterColumns:
    - description: Insecure
      jsonPath: .spec.insecure
      name: insecure
      type: boolean
    - description: Mirroring
      jsonPath: .spec.mirror
      name: mirror
      type: boolean
    - description: Current image source
      jsonPath: .spec.from
      name: from
      type: string
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              from:
                type: string
              mirror:
                type: boolean
              insecure:
                type: boolean
          status:
            type: object
            properties:
              hashReferences:
                type: array
                nullable: true
                items:
                  type: object
                  properties:
                    from:
                      type: string
                    importedAt:
                      type: string
                    imageReference:
                      type: string
