apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: tagger
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tagger
rules:
- apiGroups:
  - ""
  resources:
  - pods 
  verbs:
  - watch
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - watch
  - get
  - list
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs:
  - watch
  - get
  - list
  - create
  - update
- apiGroups: 
  - apps
  resources: 
  - replicasets
  - deployments
  verbs:
  - watch
  - get
  - list
  - update
- apiGroups:
  - tagger.dev
  resources:
  - tags
  - tags/status
  verbs:
  - "*"
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tagger
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: tagger
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: tagger
  apiGroup: rbac.authorization.k8s.io
