---
apiVersion: v1
kind: Secret
metadata:
  name: mirror-registry-config
  namespace: {{ .Release.Namespace }}
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: mirror-sign-config
  namespace: {{ .Release.Namespace }}
data: {}
