---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhooks
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: imageio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
