---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: tagger
  namespace: tagger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tagger
rules:
- apiGroups: 
  - ""
  resources: 
  - configmaps
  - secrets
  verbs:
  - watch
  - get
  - list
- apiGroups: 
  - apps
  resources: 
  - replicasets
  - deployments
  verbs:
  - watch
  - get
  - list
  - update
- apiGroups:
  - images.io
  resources:
  - tags
  verbs:
  - "*"
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tagger
  namespace: tagger
subjects:
- kind: ServiceAccount
  name: tagger
  namespace: tagger
roleRef:
  kind: ClusterRole
  name: tagger
  apiGroup: rbac.authorization.k8s.io
