apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tagger
webhooks:
- name: core.images.io
  admissionReviewVersions:
  - v1
  sideEffects: None
  clientConfig:
    service:
      name: webhooks
      namespace: tagger
      path: "/pod"
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoVENDQW0yZ0F3SUJBZ0lVT2t1ZXU2U1pD
      Z2ZIZEdsdU45Wk8xVXgxYWs4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hURUxNQWtHQTFVRUJoTUNU
      a3d4Q3pBSkJnTlZCQWdNQWs1SU1SSXdFQVlEVlFRSERBbElhV3gyWlhKegpkVzB4RHpBTkJnTlZC
      QW9NQmxSaFoyZGxjakVjTUJvR0ExVUVBd3dUZDJWaWFHOXZhM011ZEdGbloyVnlMbk4yCll6QWVG
      dzB5TURFeE1UQXhPRFU0TkRoYUZ3MHpNREE0TVRBeE9EVTRORGhhTUYweEN6QUpCZ05WQkFZVEFr
      NU0KTVFzd0NRWURWUVFJREFKT1NERVNNQkFHQTFVRUJ3d0pTR2xzZG1WeWMzVnRNUTh3RFFZRFZR
      UUtEQVpVWVdkbgpaWEl4SERBYUJnTlZCQU1NRTNkbFltaHZiMnR6TG5SaFoyZGxjaTV6ZG1Nd2dn
      RWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEcVR2YUxITTJaUW4yUmRG
      RUM0RG16UGx1ZVRNQk9OM2pYcHdzUUJJR1oKUWZPc3ZmbHJIN0tSc1FnaW11dVI5Qml1cTJXSVBq
      VC9RK0preDNFUkJuUWdxeFJiR2hvY1pHbG9tdjkrd2w4eAowdXBDSzI2a1dEc1dWWk9sM1BNV2dv
      c3NtQ2xCZ3BRaCtOcTJNZU8rc2xGcXJKcFRvN2FwSEFWSE1rYWlPQnN4CmVxTTN5Q1BZY1p4WGtz
      ZlRPcG94cHlpVDVGZmthRkdjRzhEU2JDVCs3cUpZdENNWmdZdVZxOEgrOGNIOGVtN00KRi91YjRF
      cVlYT0RJNGZqZlJ3ZmlhM0RkZzVNL0tJeXhqdWFXVFhsZW5QVFdEUmcwM3BCS256VlJzVE1vZXN1
      NQpaeVhrQXM4NTFlY3A0WCtjMUh3WVNzVmtCMFdhVHNnTEpvckhKN0lnS2pENUFnTUJBQUdqUFRB
      N01Ea0dBMVVkCkVRUXlNRENDRTNkbFltaHZiMnR6TG5SaFoyZGxjaTV6ZG1PQ0QzZGxZbWh2YjJ0
      ekxuUmhaMmRsY29JSWQyVmkKYUc5dmEzTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRndTTzFE
      VkZIaEtIUVAvWnVmckJ2UW50RTlJcE9NMgpuYldSQjVlakNwNEl4WDh1TGkyZ1hjVFAyN3RSWGJT
      ZWNqSUV1ZTJ0MHNhZEhKMGRRUXE4MjFYcmZOVUxQdHNGCngrMXJQUmpPQnNKeW04RVEwNmhUN0dV
      OHN0RENQWFpRazdZK1FUa1hPSExzWFJQbFVQNFcyS1ZVVEtDcW5OZjYKdGZlaGhzcVBQT2dLOTlD
      SksrUTA5cEZkcWdiSmllR0ZiZzBpbzh3Nm9uUUdsUk16a3dxL08zNEhWbXhjRTExVQovbFVvSU1Z
      K2NoU1YrdU1RNXd5cnJwN3BjRXNIdmFZQ1lndVZPRS9vcXF1VUg5dFFKUUs1UjRTZ0dzMFU3elM4
      ClZUaHdnME1SdmdEZURzbUVrSkk0TmE1dXJoY2UxZlhGa3NQc1g2MlFmWElXWXNCMGQvYWtabEU9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - "v1"
    resources: 
    - pods
    operations: 
    - CREATE
- name: tag.images.io
  admissionReviewVersions:
  - v1
  sideEffects: None
  clientConfig:
    service:
      name: webhooks
      namespace: tagger
      path: "/tag"
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoVENDQW0yZ0F3SUJBZ0lVT2t1ZXU2U1pD
      Z2ZIZEdsdU45Wk8xVXgxYWs4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hURUxNQWtHQTFVRUJoTUNU
      a3d4Q3pBSkJnTlZCQWdNQWs1SU1SSXdFQVlEVlFRSERBbElhV3gyWlhKegpkVzB4RHpBTkJnTlZC
      QW9NQmxSaFoyZGxjakVjTUJvR0ExVUVBd3dUZDJWaWFHOXZhM011ZEdGbloyVnlMbk4yCll6QWVG
      dzB5TURFeE1UQXhPRFU0TkRoYUZ3MHpNREE0TVRBeE9EVTRORGhhTUYweEN6QUpCZ05WQkFZVEFr
      NU0KTVFzd0NRWURWUVFJREFKT1NERVNNQkFHQTFVRUJ3d0pTR2xzZG1WeWMzVnRNUTh3RFFZRFZR
      UUtEQVpVWVdkbgpaWEl4SERBYUJnTlZCQU1NRTNkbFltaHZiMnR6TG5SaFoyZGxjaTV6ZG1Nd2dn
      RWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEcVR2YUxITTJaUW4yUmRG
      RUM0RG16UGx1ZVRNQk9OM2pYcHdzUUJJR1oKUWZPc3ZmbHJIN0tSc1FnaW11dVI5Qml1cTJXSVBq
      VC9RK0preDNFUkJuUWdxeFJiR2hvY1pHbG9tdjkrd2w4eAowdXBDSzI2a1dEc1dWWk9sM1BNV2dv
      c3NtQ2xCZ3BRaCtOcTJNZU8rc2xGcXJKcFRvN2FwSEFWSE1rYWlPQnN4CmVxTTN5Q1BZY1p4WGtz
      ZlRPcG94cHlpVDVGZmthRkdjRzhEU2JDVCs3cUpZdENNWmdZdVZxOEgrOGNIOGVtN00KRi91YjRF
      cVlYT0RJNGZqZlJ3ZmlhM0RkZzVNL0tJeXhqdWFXVFhsZW5QVFdEUmcwM3BCS256VlJzVE1vZXN1
      NQpaeVhrQXM4NTFlY3A0WCtjMUh3WVNzVmtCMFdhVHNnTEpvckhKN0lnS2pENUFnTUJBQUdqUFRB
      N01Ea0dBMVVkCkVRUXlNRENDRTNkbFltaHZiMnR6TG5SaFoyZGxjaTV6ZG1PQ0QzZGxZbWh2YjJ0
      ekxuUmhaMmRsY29JSWQyVmkKYUc5dmEzTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRndTTzFE
      VkZIaEtIUVAvWnVmckJ2UW50RTlJcE9NMgpuYldSQjVlakNwNEl4WDh1TGkyZ1hjVFAyN3RSWGJT
      ZWNqSUV1ZTJ0MHNhZEhKMGRRUXE4MjFYcmZOVUxQdHNGCngrMXJQUmpPQnNKeW04RVEwNmhUN0dV
      OHN0RENQWFpRazdZK1FUa1hPSExzWFJQbFVQNFcyS1ZVVEtDcW5OZjYKdGZlaGhzcVBQT2dLOTlD
      SksrUTA5cEZkcWdiSmllR0ZiZzBpbzh3Nm9uUUdsUk16a3dxL08zNEhWbXhjRTExVQovbFVvSU1Z
      K2NoU1YrdU1RNXd5cnJwN3BjRXNIdmFZQ1lndVZPRS9vcXF1VUg5dFFKUUs1UjRTZ0dzMFU3elM4
      ClZUaHdnME1SdmdEZURzbUVrSkk0TmE1dXJoY2UxZlhGa3NQc1g2MlFmWElXWXNCMGQvYWtabEU9
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - apiGroups:
    - "images.io"
    apiVersions:
    - "v1"
    resources: 
    - tags
    operations: 
    - CREATE
    - UPDATE
