apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tagger
webhooks:
- name: core.images.io
  admissionReviewVersions:
  - v1
  sideEffects: None
  clientConfig:
    service:
      name: mutating-webhooks
      namespace: tagger
      path: "/pod"
      port: 8080
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzakNDQXBxZ0F3SUJBZ0lVZEpWWTBPNDB2
      YlNVYjlObTcyZXA3b0Q1cXNnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNU
      a3d4Q3pBSkJnTlZCQWdNQWs1SU1SSXdFQVlEVlFRSERBbElhV3gyWlhKegpkVzB4RHpBTkJnTlZC
      QW9NQmxSaFoyZGxjakVsTUNNR0ExVUVBd3djYlhWMFlYUnBibWN0ZDJWaWFHOXZhM011CmRHRm5a
      MlZ5TG5OMll6QWVGdzB5TURFeE1UY3hNRFF4TUROYUZ3MHpNREE0TVRjeE1EUXhNRE5hTUdZeEN6
      QUoKQmdOVkJBWVRBazVNTVFzd0NRWURWUVFJREFKT1NERVNNQkFHQTFVRUJ3d0pTR2xzZG1WeWMz
      VnRNUTh3RFFZRApWUVFLREFaVVlXZG5aWEl4SlRBakJnTlZCQU1NSEcxMWRHRjBhVzVuTFhkbFlt
      aHZiMnR6TG5SaFoyZGxjaTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dn
      RUtBb0lCQVFEUkIvN1dSSXhVQzI5eW5wU2YKLzROdExET3ROcUR1eE1QQXJZSkJuZDF5SllVQ3Ja
      L01qTS9oUGtHbkxhcS9Gc29lVThldUhtQ2VVZVBJNmMwVQpTSitkc0k5ck5MbVhwQkYyRnJmd2Ni
      ZEJUbWo4YWdRMWZTY0dpODdkRGxhTTVscUpDYmViMHlKLzdoNU5oU0duCmJ3V3p3TXFCSXZPTk01
      T2xmVDRLWktBcytYZEdzb2dMcFF1NEdGWHUxNExDR2V2MWRYUVYwUTRBelh0Zkp1ZkwKSG1tUUd6
      SUFQZFlmdlhCbmZwYlJBeDFqaXhGRnN1WGc0bEJoQ0JweVFqL3ZIdVdGbkM1c0ZUcWU2b3FaT2Fm
      QQpPaGllUTFpVDk2U0hBR0k2VjhraVpZR3o2eURLWWxTaHp4bmFyeU4wQXlZb295Rk9GeTNwcUpJ
      VmdUTEVmZE45CmFmRDVBZ01CQUFHaldEQldNRlFHQTFVZEVRUk5NRXVDSEcxMWRHRjBhVzVuTFhk
      bFltaHZiMnR6TG5SaFoyZGwKY2k1emRtT0NHRzExZEdGMGFXNW5MWGRsWW1odmIydHpMblJoWjJk
      bGNvSVJiWFYwWVhScGJtY3RkMlZpYUc5dgphM013RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURR
      RUliWm0zTmVKSW5oem5JWmRNOVFJZVhLQzZVY0lGMTVCCjRucnRNNHlmODFqTWpkek1JWkE0SWU3
      UUxVN1JrRVdYaU05eVhQSThpUmwrNWxIaUQwdENHclFhc1o1b3VLZjgKcWJDaEpSaDY3b2FjcmJ0
      NVhpbk9NaC9JNzVDMHRWOXlDUjY0REZPOTY4LzlmMnROSCsyR2h4aG4xWm5RV2h3RApyTWt1UUli
      QmZabExFbkJjdnpTc1NTYW1OSzJ2SUdxek80ODV1V0NoU2RNaU1OdHpTQzdycEhub1hBeXU4V2xv
      CmdySWhjMElJKzIyRkZ2REJPdUt2LzRTeUZnQVhoaUlicVYxajgzV2F3eTJLZitBZ0FiV2puK3BL
      Qm4xNWRtTWMKU3RRR3BNUFJzdDBibTl1bUhNbElkZ2xZMzAyUzBQTzZWSTVqaTNLOTBhUWgzOHQ3
      SmRvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - "v1"
    resources: 
    - pods
    operations: 
    - CREATE
- name: tag.images.io
  admissionReviewVersions:
  - v1
  sideEffects: None
  clientConfig:
    service:
      name: mutating-webhooks
      namespace: tagger
      path: "/tag"
      port: 8080
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzakNDQXBxZ0F3SUJBZ0lVZEpWWTBPNDB2
      YlNVYjlObTcyZXA3b0Q1cXNnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNU
      a3d4Q3pBSkJnTlZCQWdNQWs1SU1SSXdFQVlEVlFRSERBbElhV3gyWlhKegpkVzB4RHpBTkJnTlZC
      QW9NQmxSaFoyZGxjakVsTUNNR0ExVUVBd3djYlhWMFlYUnBibWN0ZDJWaWFHOXZhM011CmRHRm5a
      MlZ5TG5OMll6QWVGdzB5TURFeE1UY3hNRFF4TUROYUZ3MHpNREE0TVRjeE1EUXhNRE5hTUdZeEN6
      QUoKQmdOVkJBWVRBazVNTVFzd0NRWURWUVFJREFKT1NERVNNQkFHQTFVRUJ3d0pTR2xzZG1WeWMz
      VnRNUTh3RFFZRApWUVFLREFaVVlXZG5aWEl4SlRBakJnTlZCQU1NSEcxMWRHRjBhVzVuTFhkbFlt
      aHZiMnR6TG5SaFoyZGxjaTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dn
      RUtBb0lCQVFEUkIvN1dSSXhVQzI5eW5wU2YKLzROdExET3ROcUR1eE1QQXJZSkJuZDF5SllVQ3Ja
      L01qTS9oUGtHbkxhcS9Gc29lVThldUhtQ2VVZVBJNmMwVQpTSitkc0k5ck5MbVhwQkYyRnJmd2Ni
      ZEJUbWo4YWdRMWZTY0dpODdkRGxhTTVscUpDYmViMHlKLzdoNU5oU0duCmJ3V3p3TXFCSXZPTk01
      T2xmVDRLWktBcytYZEdzb2dMcFF1NEdGWHUxNExDR2V2MWRYUVYwUTRBelh0Zkp1ZkwKSG1tUUd6
      SUFQZFlmdlhCbmZwYlJBeDFqaXhGRnN1WGc0bEJoQ0JweVFqL3ZIdVdGbkM1c0ZUcWU2b3FaT2Fm
      QQpPaGllUTFpVDk2U0hBR0k2VjhraVpZR3o2eURLWWxTaHp4bmFyeU4wQXlZb295Rk9GeTNwcUpJ
      VmdUTEVmZE45CmFmRDVBZ01CQUFHaldEQldNRlFHQTFVZEVRUk5NRXVDSEcxMWRHRjBhVzVuTFhk
      bFltaHZiMnR6TG5SaFoyZGwKY2k1emRtT0NHRzExZEdGMGFXNW5MWGRsWW1odmIydHpMblJoWjJk
      bGNvSVJiWFYwWVhScGJtY3RkMlZpYUc5dgphM013RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURR
      RUliWm0zTmVKSW5oem5JWmRNOVFJZVhLQzZVY0lGMTVCCjRucnRNNHlmODFqTWpkek1JWkE0SWU3
      UUxVN1JrRVdYaU05eVhQSThpUmwrNWxIaUQwdENHclFhc1o1b3VLZjgKcWJDaEpSaDY3b2FjcmJ0
      NVhpbk9NaC9JNzVDMHRWOXlDUjY0REZPOTY4LzlmMnROSCsyR2h4aG4xWm5RV2h3RApyTWt1UUli
      QmZabExFbkJjdnpTc1NTYW1OSzJ2SUdxek80ODV1V0NoU2RNaU1OdHpTQzdycEhub1hBeXU4V2xv
      CmdySWhjMElJKzIyRkZ2REJPdUt2LzRTeUZnQVhoaUlicVYxajgzV2F3eTJLZitBZ0FiV2puK3BL
      Qm4xNWRtTWMKU3RRR3BNUFJzdDBibTl1bUhNbElkZ2xZMzAyUzBQTzZWSTVqaTNLOTBhUWgzOHQ3
      SmRvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - apiGroups:
    - "images.io"
    apiVersions:
    - "v1"
    resources: 
    - tags
    operations: 
    - CREATE
    - UPDATE
