---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: tags.images.io
spec:
  group: images.io
  names:
    kind: Tag
    listKind: TagList
    plural: tags
    singular: tag
    shortNames:
    - tg
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            from:
              type: string
            generation:
              type: integer
        status:
          type: object
          properties:
            generation:
              type: integer
            references:
              type: array
              items:
                type: object
                properties:
                  generation:
                    type: integer
                  from:
                    type: string
                  importedAt:
                    type: string
                  imageReference:
                    type: string
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
