---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhooks
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quay-webhooks
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: docker-webhooks
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: tagio
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: tagio-external
spec:
  type: LoadBalancer
  selector:
    app: tagger
  ports:
    - port: 8083
      targetPort: 8083
