apiVersion: tagger.dev/v1beta1
kind: Image
metadata:
  name: alpine-mirror
spec:
  from: docker.io/library/alpine:latest
  mirror: true
  insecure: false
status:
  hashReferences:
  - from: docker.io/library/alpine:latest
