---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhooks
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quay-webhooks 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: docker-webhooks 
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8082 
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: tagio
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tagger
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
