---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image-tag: "yes-please"
  name: app 
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: webserver
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: app
