// Copyright 2020 The Tagger Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: infra/pb/image.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageIOService_Pull_FullMethodName = "/pb.ImageIOService/Pull"
	ImageIOService_Push_FullMethodName = "/pb.ImageIOService/Push"
)

// ImageIOServiceClient is the client API for ImageIOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ImageIOService is an service capable of Pull and Push files (we treat the operations as Pull
// and Push as we generally deal with container images). Pull receives a Packet with a Header
// and returns multiple Packets with Chunks of the file. Opossite of Pull is Push.
type ImageIOServiceClient interface {
	Pull(ctx context.Context, in *Packet, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Packet], error)
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Packet, Packet], error)
}

type imageIOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageIOServiceClient(cc grpc.ClientConnInterface) ImageIOServiceClient {
	return &imageIOServiceClient{cc}
}

func (c *imageIOServiceClient) Pull(ctx context.Context, in *Packet, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Packet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageIOService_ServiceDesc.Streams[0], ImageIOService_Pull_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, Packet]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageIOService_PullClient = grpc.ServerStreamingClient[Packet]

func (c *imageIOServiceClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Packet, Packet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageIOService_ServiceDesc.Streams[1], ImageIOService_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, Packet]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageIOService_PushClient = grpc.ClientStreamingClient[Packet, Packet]

// ImageIOServiceServer is the server API for ImageIOService service.
// All implementations must embed UnimplementedImageIOServiceServer
// for forward compatibility.
//
// ImageIOService is an service capable of Pull and Push files (we treat the operations as Pull
// and Push as we generally deal with container images). Pull receives a Packet with a Header
// and returns multiple Packets with Chunks of the file. Opossite of Pull is Push.
type ImageIOServiceServer interface {
	Pull(*Packet, grpc.ServerStreamingServer[Packet]) error
	Push(grpc.ClientStreamingServer[Packet, Packet]) error
	mustEmbedUnimplementedImageIOServiceServer()
}

// UnimplementedImageIOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageIOServiceServer struct{}

func (UnimplementedImageIOServiceServer) Pull(*Packet, grpc.ServerStreamingServer[Packet]) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedImageIOServiceServer) Push(grpc.ClientStreamingServer[Packet, Packet]) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedImageIOServiceServer) mustEmbedUnimplementedImageIOServiceServer() {}
func (UnimplementedImageIOServiceServer) testEmbeddedByValue()                        {}

// UnsafeImageIOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageIOServiceServer will
// result in compilation errors.
type UnsafeImageIOServiceServer interface {
	mustEmbedUnimplementedImageIOServiceServer()
}

func RegisterImageIOServiceServer(s grpc.ServiceRegistrar, srv ImageIOServiceServer) {
	// If the following call pancis, it indicates UnimplementedImageIOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageIOService_ServiceDesc, srv)
}

func _ImageIOService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Packet)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageIOServiceServer).Pull(m, &grpc.GenericServerStream[Packet, Packet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageIOService_PullServer = grpc.ServerStreamingServer[Packet]

func _ImageIOService_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageIOServiceServer).Push(&grpc.GenericServerStream[Packet, Packet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageIOService_PushServer = grpc.ClientStreamingServer[Packet, Packet]

// ImageIOService_ServiceDesc is the grpc.ServiceDesc for ImageIOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageIOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ImageIOService",
	HandlerType: (*ImageIOServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _ImageIOService_Pull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Push",
			Handler:       _ImageIOService_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "infra/pb/image.proto",
}
