// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TagIOServiceClient is the client API for TagIOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TagIOServiceClient interface {
	Pull(ctx context.Context, in *Packet, opts ...grpc.CallOption) (TagIOService_PullClient, error)
	Push(ctx context.Context, opts ...grpc.CallOption) (TagIOService_PushClient, error)
}

type tagIOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTagIOServiceClient(cc grpc.ClientConnInterface) TagIOServiceClient {
	return &tagIOServiceClient{cc}
}

func (c *tagIOServiceClient) Pull(ctx context.Context, in *Packet, opts ...grpc.CallOption) (TagIOService_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &TagIOService_ServiceDesc.Streams[0], "/pb.TagIOService/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &tagIOServicePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TagIOService_PullClient interface {
	Recv() (*Packet, error)
	grpc.ClientStream
}

type tagIOServicePullClient struct {
	grpc.ClientStream
}

func (x *tagIOServicePullClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tagIOServiceClient) Push(ctx context.Context, opts ...grpc.CallOption) (TagIOService_PushClient, error) {
	stream, err := c.cc.NewStream(ctx, &TagIOService_ServiceDesc.Streams[1], "/pb.TagIOService/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &tagIOServicePushClient{stream}
	return x, nil
}

type TagIOService_PushClient interface {
	Send(*Packet) error
	CloseAndRecv() (*Packet, error)
	grpc.ClientStream
}

type tagIOServicePushClient struct {
	grpc.ClientStream
}

func (x *tagIOServicePushClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tagIOServicePushClient) CloseAndRecv() (*Packet, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TagIOServiceServer is the server API for TagIOService service.
// All implementations must embed UnimplementedTagIOServiceServer
// for forward compatibility
type TagIOServiceServer interface {
	Pull(*Packet, TagIOService_PullServer) error
	Push(TagIOService_PushServer) error
	mustEmbedUnimplementedTagIOServiceServer()
}

// UnimplementedTagIOServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTagIOServiceServer struct {
}

func (UnimplementedTagIOServiceServer) Pull(*Packet, TagIOService_PullServer) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedTagIOServiceServer) Push(TagIOService_PushServer) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedTagIOServiceServer) mustEmbedUnimplementedTagIOServiceServer() {}

// UnsafeTagIOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagIOServiceServer will
// result in compilation errors.
type UnsafeTagIOServiceServer interface {
	mustEmbedUnimplementedTagIOServiceServer()
}

func RegisterTagIOServiceServer(s grpc.ServiceRegistrar, srv TagIOServiceServer) {
	s.RegisterService(&TagIOService_ServiceDesc, srv)
}

func _TagIOService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Packet)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TagIOServiceServer).Pull(m, &tagIOServicePullServer{stream})
}

type TagIOService_PullServer interface {
	Send(*Packet) error
	grpc.ServerStream
}

type tagIOServicePullServer struct {
	grpc.ServerStream
}

func (x *tagIOServicePullServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func _TagIOService_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TagIOServiceServer).Push(&tagIOServicePushServer{stream})
}

type TagIOService_PushServer interface {
	SendAndClose(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type tagIOServicePushServer struct {
	grpc.ServerStream
}

func (x *tagIOServicePushServer) SendAndClose(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tagIOServicePushServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TagIOService_ServiceDesc is the grpc.ServiceDesc for TagIOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagIOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TagIOService",
	HandlerType: (*TagIOServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _TagIOService_Pull_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Push",
			Handler:       _TagIOService_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "infra/pb/tagio.proto",
}
