name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: quay.io/rmarasch/tagger-base-image:latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build tagger
      run: go build -mod vendor -v ./cmd/tagger

    - name: Build kubectl-tag
      run: go build -mod vendor -v ./cmd/kubectl-tag

    - name: Test
      run: go test -mod vendor -v ./...
