---
name: main

on:
  push:
    branches:
      - main

jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        push: false
        context: ./
        file: ./Containerfile
        tags: quay.io/tagger/operator:latest

    - name: Save image locally
      run: |-
        docker save quay.io/tagger/operator:latest -o image.tar
        tar -czvf image.tgz image.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: image
        path: ./image.tgz

  release:
    name: Build development release
    needs:
    - image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Build linux plugin
      run: make kubectl-image

    - name: Compress linux plugin
      run: tar -C output/bin -czvf kubectl-image-linux-amd64.tgz kubectl-image

    - name: Build darwin plugin
      run: make kubectl-image-darwin

    - name: Compress darwin plugin
      run: tar -C output/bin -czvf kubectl-image-darwin-amd64.tgz kubectl-image

    - name: Build helm chart release
      run: helm package chart/

    - name: Download image artifact
      uses: actions/download-artifact@v5
      with:
        name: image
        path: ./

    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: latest
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        title: development release build
        files: |
          *.tgz
