name: pullrequest

on:
  pull_request:
    branches:
      - main

jobs:
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out code
      uses: actions/checkout@v5

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.25'

    - name: Run vet
      run: go vet ./...

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out source code
      uses: actions/checkout@v5

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.25'

    - name: Run tests
      run: go test -v ./...

  build:
    name: Build all binaries
    needs:
    - vet
    - unit
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out code
      uses: actions/checkout@v5

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.25'

    - name: Build all
      run: make build

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Install kind
      uses: helm/kind-action@v1
      with:
        cluster_name: kind

    - name: Build image
      id: push
      uses: docker/build-push-action@v6
      with:
        push: false
        context: ./
        file: ./Containerfile
        tags: quay.io/tagger/operator:pr-${{ github.event.number }}

    - name: Load image into kind cluster
      run: |-
        kind load docker-image quay.io/tagger/operator:pr-${{ github.event.number }}

    - name: Create tagger namespace
      run: |-
        kubectl create namespace tagger
        kubectl config set-context --current --namespace=tagger

    - name: Install kuttl
      run: |-
        curl -o kuttl -L https://github.com/kudobuilder/kuttl/releases/download/v0.22.0/kubectl-kuttl_0.22.0_linux_x86_64
        chmod 755 kuttl

    - name: Install helm chart
      run: |-
        helm install --debug --wait \
          --set image=quay.io/tagger/operator:pr-${{ github.event.number }} \
          --set imagePullPolicy=Never \
          --set loadBalancer=false \
          tagger ./chart

    - name: Run integration tests
      run: ./kuttl test --timeout=180 e2e

    - name: Collect information for debugging
      if: failure()
      run: |-
        kubectl get pods -n tagger -o yaml || true
        kubectl get deployments -n tagger -o yaml || true
        kubectl logs -n tagger deploy/tagger || true
