name: pullrequest

on:
  pull_request:
    branches:
      - main

jobs:
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out code
      uses: actions/checkout@v6

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.26'

    - name: Run vet
      run: go vet ./...

  staticcheck:
    name: Static check
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out source code
      uses: actions/checkout@v6

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.26'

    - name: Run static check
      run: |-
        go tool staticcheck ./...

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out source code
      uses: actions/checkout@v6

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.26'

    - name: Run tests
      run: go test -v ./...

  build:
    name: Build all binaries
    needs:
    - vet
    - unit
    - staticcheck
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libbtrfs-dev libgpgme-dev -y

    - name: Check out code
      uses: actions/checkout@v6

    - name: Install go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.26'

    - name: Build all
      run: make build

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |-
        curl -o kind -L https://github.com/kubernetes-sigs/kind/releases/download/v0.30.0/kind-linux-amd64
        chmod 755 kind && mv kind /usr/local/bin/kind
        curl -o kuttl -L https://github.com/kudobuilder/kuttl/releases/download/v0.22.0/kubectl-kuttl_0.22.0_linux_x86_64
        chmod 755 kuttl && mv kuttl /usr/local/bin/kuttl

    # we need to control the ip addresses used so we can properly deploy
    # the metal lb later on so we pre-create the kind network. for the
    # tests purpose this network does not need to be very large.
    - name: Create kind network
      run: |-
        docker network create \
          --gateway "172.18.100.1" \
          --scope "local" \
          --driver "bridge" \
          --subnet "172.18.100.0/24" \
          --ipv4 \
          kind

    - name: Create kind cluster
      run: |-
        make create-test-cluster

    - name: Build image
      id: push
      uses: docker/build-push-action@v7
      with:
        push: false
        context: ./
        file: ./Containerfile
        tags: quay.io/tagger/operator:pr-${{ github.event.number }}

    - name: Load image into kind cluster
      run: |-
        kind load docker-image quay.io/tagger/operator:pr-${{ github.event.number }}

    - name: Create tagger namespace
      run: |-
        kubectl create namespace tagger
        kubectl config set-context --current --namespace=tagger

    - name: Install helm chart
      run: |-
        helm install --debug --wait \
          --set image=quay.io/tagger/operator:pr-${{ github.event.number }} \
          --set imagePullPolicy=Never \
          tagger ./chart

    - name: Run integration tests
      run: kuttl test --timeout=180 e2e

    - name: Collect information for debugging
      if: failure()
      run: |-
        kubectl get pods -n tagger -o yaml || true
        kubectl get deployments -n tagger -o yaml || true
        kubectl logs -n tagger deploy/tagger || true
