---
name: pullrequest

on:
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: quay.io/tagger/actions-image:latest
    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: run linter
      run: golint -set_exit_status ./cmd/kubectl-tag ./cmd/tagger ./cmd/depctrl ./controllers/... ./services/...

  unit:
    name: unit
    runs-on: ubuntu-latest
    container:
      image: quay.io/tagger/actions-image:latest
    steps:
    - name: check out source code
      uses: actions/checkout@v2

    - name: run tests
      run: go test -mod vendor -v ./...

  build:
    name: build
    needs:
      - lint
      - unit
    runs-on: ubuntu-latest
    container:
      image: quay.io/tagger/actions-image:latest
    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: build all
      run: make build

  release:
    name: release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: get pr number
        id: get_pr_number
        run: echo ::set-output name=prnr::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Containerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/tagger:pr-${{ steps.get_pr_number.outputs.prnr }}

      - name: setting image repository in chart
        run: sed -i 's/ricardomaraschini/${{ github.actor }}/g' chart/values.yaml

      - name: setting image tag in chart
        run: sed -i 's/latest/pr-${{ steps.get_pr_number.outputs.prnr }}/g' chart/values.yaml

      - name: create helm artifact
        uses: actions/upload-artifact@v2
        with:
          name: helm-chart
          path: chart
