---
name: "stable-release"
on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagger Helm Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: sed -i 's/RELEASE/${{ steps.get_tag.outputs.tag }}/g' assets/helm-chart/values.yaml
      - run: tar -C assets -czvf helm-chart.tgz helm-chart
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            helm-chart.tgz
