---
name: tag

on:
  push:
    tags:
      - "v*"

jobs:
  image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Registry login
        uses: docker/login-action@v3 
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract current tag
        id: get_tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args:
            version=${{ steps.get_tag.outputs.tag }}
          context: ./
          file: ./Containerfile
          tags: quay.io/tagger/operator:${{ steps.get_tag.outputs.tag }}

  release:
    name: Create release
    needs:
    - image
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v5

    - name: Install dependencies
      run: |-
        sudo apt install pandoc texlive-full -y

    - name: Extract current tag
      id: get_tag
      run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build linux plugin
      run: VERSION=${{ steps.get_tag.outputs.tag }} make kubectl-image

    - name: Compress linux plugin
      run: tar -C output/bin -czvf kubectl-image-linux-amd64.tgz kubectl-image

    - name: Build darwin plugin
      run: VERSION=${{ steps.get_tag.outputs.tag }} make kubectl-image-darwin

    - name: Compress darwin plugin
      run: tar -C output/bin -czvf kubectl-image-darwin-amd64.tgz kubectl-image

    - name: Setting image tag in values.yaml
      run: sed -i 's/latest/${{ steps.get_tag.outputs.tag }}/g' chart/values.yaml

    - name: Setting version in chart.yaml
      run: sed -i 's/v0.0.0/${{ steps.get_tag.outputs.tag }}/g' chart/Chart.yaml

    - name: Build helm chart release
      run: helm package chart/

    - name: Build documentation
      run: make pdf

    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |-
          *.tgz
          output/doc/README.pdf
